version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 3001:3000
    container_name: frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3000