version: '3.9'

services:
  nginx:
    depends_on:
      - frontend
      - backend
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 5000:80
    container_name: reverse-proxy

  frontend:
    build:
      context: ./todo-frontend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    ports:
      - 3001:3000
    container_name: frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000/api/

  backend:
    build:
      context: ./todo-backend/
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./todo-backend:/usr/src/app
    environment:
      - REDIS_URL=//redis:6379
      - MONGO_URL=mongodb://root:secret@mongo:27017/todo_db
    container_name: backend

  mongo:
    image: mongo
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: todo_db
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
    container_name: mongo

  redis:
    image: redis
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data
    container_name: redis
  
  debug-helper:
    image: busybox